### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_linter_settings'

### ISSUE THREAD

**Issue by heikki** [kaste/SublimeLinter-addon-toggler#1]
I get this error when trying to toggle linters:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1036, in run_
    return self.run()
  File "plugin in /Users/heikki/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-addon-toggler.sublime-package", line 10, in run
  File "plugin in /Users/heikki/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-addon-toggler.sublime-package", line 37, in collect_possible_linters
AttributeError: 'module' object has no attribute 'get_linter_settings'
```

**Comment by kaste** [comment]
Oh, sorry. I thought that has already shipped. 

So I probably should post that this works with the next SL release or master.

**Comment by heikki** [comment]
Ok, that explains :)

**Comment by kaste** [comment]
We finally pushed SublimeLinter 4.3. So I think you can try again.
